### ISSUE TITLE
历史请求body没有保存

### ISSUE THREAD

**Issue by duan2ping** [wisdom-projects/rest-client#10]
不知道是不是我使用方式不对，还是该软件没有设计这个功能。历史请求保存了URL但是对应URL的body相关参数未保存，导致保存的历史URL毫无意义。

**Comment by Dom-Wang** [comment]
估计你用的不是Wisdom restclient，你下载这个JAR包执行试试
https://github.com/wisdom-projects/rest-client/tree/master/tools
