### ISSUE TITLE
软件许可证没在Github存储库显示

### ISSUE THREAD

**Issue by takato1314** [wisdom-projects/rest-client#7]
首先，我想感谢开发人员在这份软件所付出的功劳。

在使用的当中，我发觉了这份软件的软件许可证有在[License](https://github.com/wisdom-projects/rest-client/blob/master/LICENSE)显示着Apache License，但是并没在主页显示
![image](https://user-images.githubusercontent.com/10910968/47488011-2303eb00-d876-11e8-8151-5565115772e2.png)

因此，我希望你能帮忙应用[以下步骤](https://stackoverflow.com/a/37895659/3104587)把软件许可证正式的在主页显示出来（重要的应该只有第三步而已）。

预期结果：
![image](https://user-images.githubusercontent.com/10910968/47488332-b4735d00-d876-11e8-90b7-faea9a1d2615.png)
![image](https://user-images.githubusercontent.com/10910968/47488352-c35a0f80-d876-11e8-9ffc-7042f509f454.png)

谢谢。

**Comment by Dom-Wang** [comment]
谢谢提示，已经更新！
