### ISSUE TITLE
Body添加数据value显示错误

### ISSUE THREAD

**Issue by duan2ping** [wisdom-projects/rest-client#9]
body添加数据时value错误

![restclient_bug](https://user-images.githubusercontent.com/22853839/62199153-93b3d700-b3b5-11e9-92e2-3368c9351255.gif)

**Comment by Dom-Wang** [comment]
用的是Wisdom restclient么？没有这个界面的

**Comment by Dom-Wang** [comment]
Wisdom restclient JAR包地址：
https://github.com/wisdom-projects/rest-client/tree/master/tools
